#!/bin/bash

echo "🚀 KALE Weather Farming - Enhanced 4-Process Demo"
echo "================================================"
echo ""
echo "🎯 This demo showcases sophisticated weather farming with:"
echo "  ✅ 30-second blocks (5-minute total cycle)"
echo "  ✅ DAO vote analysis and user decision-making"
echo "  ✅ Plant vs Store agriculture mechanics"
echo "  ✅ Realistic wager and reward pools"
echo "  ✅ Detailed profit/loss calculations"
echo ""
echo "🎮 Game Phases:"
echo "  📍 Blocks 1-5: Wager + Agriculture (Plant/Store) phase"
echo "  📍 Block 6:    Location reveal + Agriculture only"  
echo "  📍 Blocks 7-9: Agriculture only (Plant/Store)"
echo "  📍 Block 10:   Weather reveal + Final settlement"
echo ""
echo "👥 Three Sophisticated Users:"
echo "  🔴 Alice: Aggressive risk-taker (trusts Bull & Technical DAOs)"
echo "  🔵 Bob:   Conservative farmer (trusts Bear & Sentiment DAOs)"
echo "  🟡 Charlie: Balanced strategist (trusts all DAOs equally)"
echo ""
echo "🚀 TO RUN THE ENHANCED DEMO:"
echo ""
echo "1️⃣  Start Backend Server (in terminal 1):"
echo "   cd demo && ./start-backend.sh"
echo ""
echo "2️⃣  Start Alice Client (in terminal 2):"
echo "   cd demo && ./start-alice.sh"
echo ""
echo "3️⃣  Start Bob Client (in terminal 3):"
echo "   cd demo && ./start-bob.sh"
echo ""
echo "4️⃣  Start Charlie Client (in terminal 4):"
echo "   cd demo && ./start-charlie.sh"
echo ""
echo "📊 What You'll See:"
echo "  🗳️  DAO votes revealed at blocks 2 & 4"
echo "  🧠 User analysis of DAO predictions"
echo "  💰 Strategic wager placement"
echo "  🌱 Plant vs Store agriculture decisions"
echo "  🌍 Location reveal at block 6"
echo "  🌤️  Weather reveal at block 10"
echo "  🏆 Detailed profit/loss breakdown"
echo ""
echo "⏰ Total Demo Duration: ~5 minutes"
echo "📡 Monitor API: curl http://localhost:4000/api/cycle/status"
echo ""
echo "🎯 This demonstrates the full sophistication of our"
echo "   KALE Weather Farming ecosystem with realistic"
echo "   decision-making and reward mechanics!"
echo ""
echo "================================================"